/*
 * This source file was generated by the Gradle 'init' task
 */
package cryptrade;

import cryptrade.Service.Market;

public class App {
    public static void main(String[] args) {
        Market.market();
    }
}
